#!/bin/bash

# source the ciop functions (e.g. ciop-log, ciop-getparam)
source ${ciop_job_include}

# define the exit codes
SUCCESS=0
ERR_NO_URL=5
ERR_COMPRESSION=30
ERR_PUBLISH=35

# add a trap to exit gracefully
function cleanExit ()
{
  local retval=$?
  local msg=""
  case "${retval}" in
    ${SUCCESS}) msg="Processing successfully concluded";;
    ${ERR_NO_URL}) msg="The Landsat 8 product online resource could not be resolved";;
    ${ERR_DOWNLOAD_1C}) msg="Failed to retrieve Sentinel-2 Level 1C product";;
    ${ERR_GRANULE_DIR}) msg="Couldn't find the Sentinel-2 Level 1C product granule directory";;
    ${ERR_SEN2COR}) msg="SEN2COR main binary L2A_Process failed";;
    ${ERR_LEVEL_2A_DIR}) msg="Couldn't find the Sentinel-2 Level 2A product";;
    ${ERR_COMPRESSION}) msg="Failed to compress the Sentinel-2 Level 2A product";;
    ${ERR_PUBLISH}) msg="Failed to publish the Sentinel-2 Level 2A product";;
    *) msg="Unknown error";;
  esac

  [ "${retval}" != "0" ] && ciop-log "ERROR" "Error ${retval} - ${msg}, processing aborted" || ciop-log "INFO" "${msg}"
  exit ${retval}
}

trap cleanExit EXIT

function setOTBenv() {
    
  . /etc/profile.d/otb.sh

  export otb_ram=4096
 # export GDAL_DATA=/usr/share/gdal/
}

function setGDALEnv() {

  export GDAL_HOME=/usr/local/gdal-t2/
  export PATH=$GDAL_HOME/bin/:$PATH
  export LD_LIBRARY_PATH=$GDAL_HOME/lib/:$LD_LIBRARY_PATH
  export GDAL_DATA=$GDAL_HOME/share/gdal

}

function getGain() {

  local band=$1

  gain=$( cat $DIR/*_MTL.txt | grep REFLECTANCE_MULT_BAND_${band} | cut -d "=" -f 2 | tr -d " " )

  echo ${gain}

}

function getOffset() {

  local band=$1

  offset=$( cat $DIR/*_MTL.txt | grep REFLECTANCE_ADD_BAND_${band} | cut -d "=" -f 2 | tr -d " " )

  echo ${offset}

}

function DNtoReflectance() {

  local band=$1
  local base_name=$2

  gain=$( getGain ${band} )
  offset=$( getOffset ${band} )

  [ ${band} -eq 4 ] && pan_band=1
  [ ${band} -eq 3 ] && pan_band=2
  [ ${band} -eq 2 ] && pan_band=3

  otbcli_BandMath \
    -progress false \
    -il ${base_name}/pan-${base_name}.tif \
    -exp "${gain} * im1b${pan_band} + ${offset}" \
    -out ${base_name}/PAN_TOA_REFLECTANCE_B${band}.TIF

}

function mapBands() {

  local vrt=$1

  xmlstarlet ed -L -a "/VRTDataset/VRTRasterBand[@band="1"]/NoDataValue" \
    -t elem -n "ColorInterp" -v "Red" \
    ${vrt}

  xmlstarlet ed -L -a "/VRTDataset/VRTRasterBand[@band="2"]/NoDataValue" \
    -t elem -n "ColorInterp" -v "Green" \
    ${vrt}

  xmlstarlet ed -L -a "/VRTDataset/VRTRasterBand[@band="3"]/NoDataValue" \
    -t elem -n "ColorInterp" -v "Blue" \
    ${vrt}
}

# DN to TOA reflectance
#gain_red=$( getGain 4 )
#gain_green=$( getGain 3 )
#gain_blue=$( getGain 2 )

#offset_red=$( getOffset 4 )
#offset_green=$( getOffset 3 )
#offset_blue=$( getOffset 2 )

function url_resolver() {

  local url=""
  local reference="$1"
  
  read identifier path < <( opensearch-client -m EOP  "${reference}" identifier,wrsLongitudeGrid | tr "," " " )
  [ -z "${path}" ] && path="$( echo ${identifier} | cut -c 4-6)"
  row="$( echo ${identifier} | cut -c 7-9)"

  url="http://storage.googleapis.com/earthengine-public/landsat/L8/${path}/${row}/${identifier}.tar.bz"

  [ -z "$( curl -s --head "${url}" | head -n 1 | grep "HTTP/1.[01] [23].." )" ] && return 1

  echo "${url}"

}


function main() {

  # set the gdal addo levels
  addo="2 4 8 16 32 64 128 256 512 1024 2048 4096 8192"

  # set OTB environment
  setOTBenv

  setGDALEnv

  cd ${TMPDIR}

  num_steps=14

  while read input
  do 
    ciop-log "INFO" "(1 of ${num_steps}) Retrieve Landsat 8 product from ${input}"

    # temporary path until eo-samples indes is ready
    read identifier startdate enddate < <( opensearch-client ${input} identifier,startdate,enddate | tr "," " " )
    online_resource="$( url_resolver ${input} || return $?)"
    [ $? != 0 ] && return ${ERR_NO_URL} 

    local_resource="$( echo ${online_resource} | ciop-copy -U -O ${TMPDIR} - )"
   
    ciop-log "INFO" "(2 of ${num_steps}) Extract ${identifier}"
    
    mkdir ${identifier}
    tar jxf ${local_resource} -C ${identifier}

    export DIR=${identifier}

    ciop-log "INFO" "(3 of ${num_steps}) Create VRT with RGB bands" 
    gdalbuildvrt \
      -separate \
      -q \
      -srcnodata "0 0 0"\
      -vrtnodata "0 0 0"\
      ${DIR}/rgb.vrt \
      ${DIR}/*B4.TIF ${DIR}/*B3.TIF ${DIR}/*B2.TIF || return ${ERR_GDAL_VRT}

    mapBands ${DIR}/rgb.vrt || return ${ERR_MAP_BANDS}

    ciop-log "INFO" "(4 of ${num_steps}) OTB BundleToPerfectSensor"
    
    otbcli_BundleToPerfectSensor \
      -progress false \
      -ram ${otb_ram} \
      -inp ${DIR}/*B8.TIF \
      -inxs ${DIR}/rgb.vrt \
      -out ${DIR}/pan-${DIR}.tif uint16 || return ${ERR_OTB_BUNDLETOPERFECTSENSOR}

    rm -f ${DIR}/rgb.vrt

    ciop-log "INFO" "(5 of ${num_steps}) Conversion of DN to reflectance"

    DNtoReflectance 4 ${DIR} || return ${ERR_DN2REF_4}
    DNtoReflectance 3 ${DIR} || return ${ERR_DN2REF_3}
    DNtoReflectance 2 ${DIR} || return ${ERR_DN2REF_2}

    rm -f ${DIR}/pan-${DIR}.tif

    ciop-log "INFO" "(6 of ${num_steps}) Create VRT with RGB pansharpened bands"

    gdalbuildvrt \
      -separate \
      -q \
      -srcnodata "0 0 0"\
      -vrtnodata "0 0 0"\
      ${DIR}/pan_rgb.vrt \
      ${DIR}/PAN*B4.TIF ${DIR}/PAN*B3.TIF ${DIR}/PAN*B2.TIF || return ${ERR_GDAL_VRT2}

    ciop-log "INFO" "(7 of ${num_steps}) Rescale to bitr"

    gdal_translate \
      -q \
      -ot Byte \
      -scale 0 1 0 255 \
      -a_nodata "0 0 0" \
      ${DIR}/pan_rgb.vrt ${DIR}/pan-${DIR}-scaled.tif || return ${ERR_GDAL_TRANSLATE}

    rm -f ${DIR}/PAN*B?.TIF

    rm -f ${DIR}/pan_rgb.vrt

    ciop-log "INFO" "(8 of ${num_steps}) Warp RGB raster"

    gdalwarp \
      -q \
      -r cubic \
      -wm ${otb_ram} \
      -multi \
      -srcnodata "0 0 0" \
      -dstnodata "0 0 0" \
      -dstalpha \
      -wo OPTIMIZE_SIZE=TRUE \
      -wo UNIFIED_SRC_NODATA=YES \
      -t_srs EPSG:4326 \
      -co tfw=yes \
      -co TILED=YES\
      -co COMPRESS=LZW\
      ${DIR}/pan-${DIR}-scaled.tif ${DIR}/pansharp_${DIR}_4326.tif || return ${ERR_GDAL_WARP}

    rm -f ${DIR}/pan-${DIR}-scaled.tif

    ciop-log "INFO" "(9 of ${num_steps}) Sigmoidal contrast"

    convert \
      -quiet \
      -sigmoidal-contrast 50x16% \
      ${DIR}/pansharp_${DIR}_4326.tif \
      ${DIR}/pansharp_${DIR}_4326_bright.tif || return ${ERR_CONVERT}

    rm -f ${DIR}/pansharp_${DIR}_4326.tif

    mv ${DIR}/pansharp_${DIR}_4326.tfw ${DIR}/pansharp_${DIR}_4326_bright.tfw

    ciop-log "INFO" "(10 of ${num_steps}) Geocoding of contrast image"   
    gdal_translate \
      -q \
      ${DIR}/pansharp_${DIR}_4326_bright.tif \
      ${DIR}/${DIR}_PANSHARP.tif || return ${ERR_GDAL_TRANSLATE2}

    rm -f ${DIR}/pansharp_${DIR}_4326_bright.tif

    ciop-log "INFO" "(11 of ${num_steps}) Create levels"
   
    gdaladdo \
      -q \
      -r cubic \
      --config COMPRESS_OVERVIEW LZW \
      ${DIR}/${DIR}_PANSHARP.tif ${addo}  || return ${ERR_GDAL_ADDO}

    rm -f ${DIR}/pansharp_${DIR}_4326_bright.tfw

    ciop-log "INFO" "(12 of ${num_steps}) Generate metadata"

    target_xml=${TMPDIR}/${DIR}/${DIR}_PANSHARP.tif.xml
    cp /application/pan-sharp/etc/eop-template.xml ${target_xml}

    # set product type
    xmlstarlet ed -L \
      -u "//EarthObservation/metaDataProperty/EarthObservationMetaData/productType" \
      -v "LC8_PANSHARP" \
      ${target_xml}    

    # set processor name
    xmlstarlet ed -L \
      -u "//EarthObservation/metaDataProperty/EarthObservationMetaData/processing/ProcessingInformation/processorName" \
      -v "dcs-landsat8-pansharpening" \
      ${target_xml}

    xmlstarlet ed -L \
      -u "//EarthObservation/metaDataProperty/EarthObservationMetaData/processing/ProcessingInformation/processorVersion" \
      -v "1.0" \
      ${target_xml}

    # set processor name
    xmlstarlet ed -L \
      -u "//EarthObservation/metaDataProperty/EarthObservationMetaData/processing/ProcessingInformation/nativeProductFormat" \
      -v "GEOTIFF" \
      ${target_xml}

    # set processor name
    xmlstarlet ed -L \
      -u "//EarthObservation/metaDataProperty/EarthObservationMetaData/processing/ProcessingInformation/processingCenter" \
      -v "Terradue Cloud Platform" \
      ${target_xml}
  
    # set startdate
    xmlstarlet ed -L \
      -u "//EarthObservation/phenomenonTime/TimePeriod/beginPosition" \
      -v "${startdate}" \
      ${target_xml}

    # set stopdate
    xmlstarlet ed -L \
      -u "//EarthObservation/phenomenonTime/TimePeriod/endPosition" \
      -v "${enddate}" \
      ${target_xml}   
  
    # set stopdate
    xmlstarlet ed -L \
      -u "" \
      -v "" \
      ${target_xml}

    ciop-log "INFO" "(13 of ${num_steps}) Publish pan-sharpened RGB image"
    ciop-publish -m ${TMPDIR}/${DIR}/${DIR}_PANSHARP.tif
    
    ciop-log "INFO" "(14 of ${num_steps}) Publish eop metadata"
    ciop-publish -m ${target_xml}
  done

}

cat | main || exit $?
